// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        R_address0,
        R_ce0,
        R_we0,
        R_d0,
        B_0_0_load,
        B_0_1_load,
        B_0_2_load,
        B_1_0_load,
        B_1_1_load,
        B_1_2_load,
        B_2_0_load,
        B_2_1_load,
        B_2_2_load,
        zext_ln40_6,
        zext_ln40_8,
        zext_ln40_10
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] R_address0;
output   R_ce0;
output   R_we0;
output  [15:0] R_d0;
input  [7:0] B_0_0_load;
input  [7:0] B_0_1_load;
input  [7:0] B_0_2_load;
input  [7:0] B_1_0_load;
input  [7:0] B_1_1_load;
input  [7:0] B_1_2_load;
input  [7:0] B_2_0_load;
input  [7:0] B_2_1_load;
input  [7:0] B_2_2_load;
input  [7:0] zext_ln40_6;
input  [7:0] zext_ln40_8;
input  [7:0] zext_ln40_10;

reg ap_idle;
reg R_ce0;
reg R_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln34_fu_173_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] zext_ln40_8_cast_fu_157_p1;
reg   [15:0] zext_ln40_8_cast_reg_307;
wire   [15:0] zext_ln40_6_cast_fu_161_p1;
reg   [15:0] zext_ln40_6_cast_reg_312;
reg   [1:0] j_reg_317;
reg   [1:0] j_reg_317_pp0_iter1_reg;
reg   [1:0] j_reg_317_pp0_iter2_reg;
reg   [1:0] j_reg_317_pp0_iter3_reg;
wire   [15:0] mul_ln40_fu_230_p2;
wire   [15:0] grp_fu_249_p3;
wire   [63:0] zext_ln43_2_fu_244_p1;
wire    ap_block_pp0_stage0;
reg   [1:0] j_1_fu_64;
wire   [1:0] add_ln34_fu_179_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j;
wire   [15:0] grp_fu_257_p3;
wire   [7:0] tmp_5_fu_185_p5;
wire   [7:0] tmp_4_fu_206_p5;
wire   [7:0] tmp_3_fu_218_p5;
wire   [7:0] mul_ln40_fu_230_p0;
wire   [7:0] mul_ln40_fu_230_p1;
wire   [2:0] zext_ln43_fu_235_p1;
wire   [2:0] add_ln43_fu_238_p2;
wire   [7:0] grp_fu_249_p0;
wire   [7:0] grp_fu_249_p1;
wire   [7:0] grp_fu_257_p0;
wire   [7:0] grp_fu_257_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_249_p00;
wire   [15:0] grp_fu_249_p10;
wire   [15:0] grp_fu_257_p00;
wire   [15:0] mul_ln40_fu_230_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U23(
    .din0(B_2_0_load),
    .din1(B_2_1_load),
    .din2(B_2_2_load),
    .din3(ap_sig_allocacmp_j),
    .dout(tmp_5_fu_185_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U24(
    .din0(B_1_0_load),
    .din1(B_1_1_load),
    .din2(B_1_2_load),
    .din3(j_reg_317),
    .dout(tmp_4_fu_206_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U25(
    .din0(B_0_0_load),
    .din1(B_0_1_load),
    .din2(B_0_2_load),
    .din3(j_reg_317_pp0_iter1_reg),
    .dout(tmp_3_fu_218_p5)
);

matrix_mult_3x3_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U26(
    .din0(mul_ln40_fu_230_p0),
    .din1(mul_ln40_fu_230_p1),
    .dout(mul_ln40_fu_230_p2)
);

matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_249_p0),
    .din1(grp_fu_249_p1),
    .din2(mul_ln40_fu_230_p2),
    .ce(1'b1),
    .dout(grp_fu_249_p3)
);

matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_257_p0),
    .din1(grp_fu_257_p1),
    .din2(grp_fu_249_p3),
    .ce(1'b1),
    .dout(grp_fu_257_p3)
);

matrix_mult_3x3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln34_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_1_fu_64 <= add_ln34_fu_179_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_64 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        j_reg_317 <= ap_sig_allocacmp_j;
        j_reg_317_pp0_iter1_reg <= j_reg_317;
        zext_ln40_6_cast_reg_312[7 : 0] <= zext_ln40_6_cast_fu_161_p1[7 : 0];
        zext_ln40_8_cast_reg_307[7 : 0] <= zext_ln40_8_cast_fu_157_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        j_reg_317_pp0_iter2_reg <= j_reg_317_pp0_iter1_reg;
        j_reg_317_pp0_iter3_reg <= j_reg_317_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_ce0 = 1'b1;
    end else begin
        R_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_we0 = 1'b1;
    end else begin
        R_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_173_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j = 2'd0;
    end else begin
        ap_sig_allocacmp_j = j_1_fu_64;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_address0 = zext_ln43_2_fu_244_p1;

assign R_d0 = grp_fu_257_p3;

assign add_ln34_fu_179_p2 = (ap_sig_allocacmp_j + 2'd1);

assign add_ln43_fu_238_p2 = (zext_ln43_fu_235_p1 + 3'd3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_249_p0 = grp_fu_249_p00;

assign grp_fu_249_p00 = tmp_5_fu_185_p5;

assign grp_fu_249_p1 = grp_fu_249_p10;

assign grp_fu_249_p10 = zext_ln40_10;

assign grp_fu_257_p0 = grp_fu_257_p00;

assign grp_fu_257_p00 = tmp_4_fu_206_p5;

assign grp_fu_257_p1 = zext_ln40_8_cast_reg_307;

assign icmp_ln34_fu_173_p2 = ((ap_sig_allocacmp_j == 2'd3) ? 1'b1 : 1'b0);

assign mul_ln40_fu_230_p0 = mul_ln40_fu_230_p00;

assign mul_ln40_fu_230_p00 = tmp_3_fu_218_p5;

assign mul_ln40_fu_230_p1 = zext_ln40_6_cast_reg_312;

assign zext_ln40_6_cast_fu_161_p1 = zext_ln40_6;

assign zext_ln40_8_cast_fu_157_p1 = zext_ln40_8;

assign zext_ln43_2_fu_244_p1 = add_ln43_fu_238_p2;

assign zext_ln43_fu_235_p1 = j_reg_317_pp0_iter3_reg;

always @ (posedge ap_clk) begin
    zext_ln40_8_cast_reg_307[15:8] <= 8'b00000000;
    zext_ln40_6_cast_reg_312[15:8] <= 8'b00000000;
end

endmodule //matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop1
