-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult_3x3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_0_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    R_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    R_ce0 : OUT STD_LOGIC;
    R_we0 : OUT STD_LOGIC;
    R_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult_3x3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_3x3_matrix_mult_3x3,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau25p-sfvb784-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.771000,HLS_SYN_LAT=29,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=288,HLS_SYN_LUT=646,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_idle : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_ready : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0 : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0 : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_idle : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_ready : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0 : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0 : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_idle : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_ready : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0 : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0 : STD_LOGIC;
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        R_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        R_ce0 : OUT STD_LOGIC;
        R_we0 : OUT STD_LOGIC;
        R_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        B_0_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_0_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_0_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_4 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        R_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        R_ce0 : OUT STD_LOGIC;
        R_we0 : OUT STD_LOGIC;
        R_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        B_0_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_0_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_0_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_8 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_10 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        R_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        R_ce0 : OUT STD_LOGIC;
        R_we0 : OUT STD_LOGIC;
        R_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        B_0_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_0_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_0_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_1_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        B_2_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_12 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_14 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln40_16 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172 : component matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start,
        ap_done => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done,
        ap_idle => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_idle,
        ap_ready => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_ready,
        R_address0 => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0,
        R_ce0 => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0,
        R_we0 => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0,
        R_d0 => grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0,
        B_0_0_load => B_0_0,
        B_0_1_load => B_0_1,
        B_0_2_load => B_0_2,
        B_1_0_load => B_1_0,
        B_1_1_load => B_1_1,
        B_1_2_load => B_1_2,
        B_2_0_load => B_2_0,
        B_2_1_load => B_2_1,
        B_2_2_load => B_2_2,
        zext_ln40 => A_0_0,
        zext_ln40_2 => A_0_1,
        zext_ln40_4 => A_0_2);

    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202 : component matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start,
        ap_done => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done,
        ap_idle => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_idle,
        ap_ready => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_ready,
        R_address0 => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0,
        R_ce0 => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0,
        R_we0 => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0,
        R_d0 => grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0,
        B_0_0_load => B_0_0,
        B_0_1_load => B_0_1,
        B_0_2_load => B_0_2,
        B_1_0_load => B_1_0,
        B_1_1_load => B_1_1,
        B_1_2_load => B_1_2,
        B_2_0_load => B_2_0,
        B_2_1_load => B_2_1,
        B_2_2_load => B_2_2,
        zext_ln40_6 => A_1_0,
        zext_ln40_8 => A_1_1,
        zext_ln40_10 => A_1_2);

    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223 : component matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start,
        ap_done => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done,
        ap_idle => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_idle,
        ap_ready => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_ready,
        R_address0 => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0,
        R_ce0 => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0,
        R_we0 => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0,
        R_d0 => grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0,
        B_0_0_load => B_0_0,
        B_0_1_load => B_0_1,
        B_0_2_load => B_0_2,
        B_1_0_load => B_1_0,
        B_1_1_load => B_1_1,
        B_1_2_load => B_1_2,
        B_2_0_load => B_2_0,
        B_2_1_load => B_2_1,
        B_2_2_load => B_2_2,
        zext_ln40_12 => A_2_0,
        zext_ln40_14 => A_2_1,
        zext_ln40_16 => A_2_2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_ready = ap_const_logic_1)) then 
                    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_ready = ap_const_logic_1)) then 
                    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_ready = ap_const_logic_1)) then 
                    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done, grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done, grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    R_address0_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0, grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0, grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_address0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            R_address0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            R_address0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0;
        else 
            R_address0 <= "XXXX";
        end if; 
    end process;


    R_ce0_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0, grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0, grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_ce0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            R_ce0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            R_ce0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0;
        else 
            R_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_d0_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0, grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0, grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_d0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            R_d0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            R_d0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0;
        else 
            R_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    R_we0_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0, grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0, grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_we0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            R_we0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            R_we0 <= grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0;
        else 
            R_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done)
    begin
        if ((grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done)
    begin
        if ((grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done)
    begin
        if ((grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start <= grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg;
    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start <= grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg;
    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start <= grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg;
end behav;
