-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult_3x3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_0_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    R_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    R_ce0 : OUT STD_LOGIC;
    R_we0 : OUT STD_LOGIC;
    R_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    R_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    R_ce1 : OUT STD_LOGIC;
    R_we1 : OUT STD_LOGIC;
    R_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult_3x3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_3x3_matrix_mult_3x3,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau25p-sfvb784-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.295000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=121,HLS_SYN_LUT=528,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal zext_ln40_4_fu_274_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_5_fu_278_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_8_fu_282_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_11_fu_286_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_14_fu_290_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_17_fu_294_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_2_fu_298_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln40_3_fu_302_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_7_fu_306_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_10_fu_310_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_13_fu_314_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln40_16_fu_318_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_fu_330_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal soma_2_fu_340_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_4_fu_350_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_6_fu_360_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_8_fu_366_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_10_fu_372_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_12_fu_382_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_14_fu_388_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_16_fu_394_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_400_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_408_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_424_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_432_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_440_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_448_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_456_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_464_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_490_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_5_reg_720 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_498_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_7_reg_725 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_506_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_9_reg_730 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_514_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_11_reg_735 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_522_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_13_reg_740 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_530_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_15_reg_745 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_538_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_17_reg_750 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_472_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_481_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_fu_330_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_1_fu_326_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_fu_330_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_fu_322_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_2_fu_340_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_6_fu_336_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_2_fu_340_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_4_fu_350_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_9_fu_346_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_4_fu_350_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_6_fu_360_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_12_fu_356_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_6_fu_360_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_8_fu_366_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_8_fu_366_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_10_fu_372_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_10_fu_372_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_12_fu_382_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_15_fu_378_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal soma_12_fu_382_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_14_fu_388_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_14_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_16_fu_394_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal soma_16_fu_394_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_400_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_400_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_408_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_408_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_416_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_416_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_424_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_424_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_432_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_432_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_440_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_440_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_448_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_448_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_456_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_456_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_464_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_464_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_472_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_472_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_481_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_481_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_490_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_490_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_498_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_498_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_506_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_506_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_514_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_514_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_522_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_522_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_530_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_530_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_538_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_538_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_3x3_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    mul_8ns_8ns_16_1_1_U1 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_fu_330_p0,
        din1 => soma_fu_330_p1,
        dout => soma_fu_330_p2);

    mul_8ns_8ns_16_1_1_U2 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_2_fu_340_p0,
        din1 => soma_2_fu_340_p1,
        dout => soma_2_fu_340_p2);

    mul_8ns_8ns_16_1_1_U3 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_4_fu_350_p0,
        din1 => soma_4_fu_350_p1,
        dout => soma_4_fu_350_p2);

    mul_8ns_8ns_16_1_1_U4 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_6_fu_360_p0,
        din1 => soma_6_fu_360_p1,
        dout => soma_6_fu_360_p2);

    mul_8ns_8ns_16_1_1_U5 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_8_fu_366_p0,
        din1 => soma_8_fu_366_p1,
        dout => soma_8_fu_366_p2);

    mul_8ns_8ns_16_1_1_U6 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_10_fu_372_p0,
        din1 => soma_10_fu_372_p1,
        dout => soma_10_fu_372_p2);

    mul_8ns_8ns_16_1_1_U7 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_12_fu_382_p0,
        din1 => soma_12_fu_382_p1,
        dout => soma_12_fu_382_p2);

    mul_8ns_8ns_16_1_1_U8 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_14_fu_388_p0,
        din1 => soma_14_fu_388_p1,
        dout => soma_14_fu_388_p2);

    mul_8ns_8ns_16_1_1_U9 : component matrix_mult_3x3_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => soma_16_fu_394_p0,
        din1 => soma_16_fu_394_p1,
        dout => soma_16_fu_394_p2);

    mac_muladd_8ns_8ns_16ns_16_4_1_U10 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_400_p0,
        din1 => grp_fu_400_p1,
        din2 => soma_fu_330_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_400_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U11 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_408_p0,
        din1 => grp_fu_408_p1,
        din2 => soma_2_fu_340_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_408_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U12 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_416_p0,
        din1 => grp_fu_416_p1,
        din2 => soma_4_fu_350_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_416_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U13 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_424_p0,
        din1 => grp_fu_424_p1,
        din2 => soma_6_fu_360_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_424_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U14 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_432_p0,
        din1 => grp_fu_432_p1,
        din2 => soma_8_fu_366_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_432_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U15 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_440_p0,
        din1 => grp_fu_440_p1,
        din2 => soma_10_fu_372_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_440_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U16 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_448_p0,
        din1 => grp_fu_448_p1,
        din2 => soma_12_fu_382_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_448_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U17 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_456_p0,
        din1 => grp_fu_456_p1,
        din2 => soma_14_fu_388_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_456_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U18 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_464_p0,
        din1 => grp_fu_464_p1,
        din2 => soma_16_fu_394_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_464_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U19 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_472_p0,
        din1 => grp_fu_472_p1,
        din2 => grp_fu_400_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_472_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U20 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_481_p0,
        din1 => grp_fu_481_p1,
        din2 => grp_fu_408_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_481_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U21 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_490_p0,
        din1 => grp_fu_490_p1,
        din2 => grp_fu_416_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_490_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U22 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_498_p0,
        din1 => grp_fu_498_p1,
        din2 => grp_fu_424_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_498_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U23 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_506_p0,
        din1 => grp_fu_506_p1,
        din2 => grp_fu_432_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_506_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U24 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_514_p0,
        din1 => grp_fu_514_p1,
        din2 => grp_fu_440_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_514_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U25 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_522_p0,
        din1 => grp_fu_522_p1,
        din2 => grp_fu_448_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_522_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U26 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_530_p0,
        din1 => grp_fu_530_p1,
        din2 => grp_fu_456_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_530_p3);

    mac_muladd_8ns_8ns_16ns_16_4_1_U27 : component matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_538_p0,
        din1 => grp_fu_538_p1,
        din2 => grp_fu_464_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_538_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                soma_11_reg_735 <= grp_fu_514_p3;
                soma_13_reg_740 <= grp_fu_522_p3;
                soma_15_reg_745 <= grp_fu_530_p3;
                soma_17_reg_750 <= grp_fu_538_p3;
                soma_5_reg_720 <= grp_fu_490_p3;
                soma_7_reg_725 <= grp_fu_498_p3;
                soma_9_reg_730 <= grp_fu_506_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;

    R_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            R_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            R_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            R_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            R_address0 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            R_address0 <= "XXXX";
        end if; 
    end process;


    R_address1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            R_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            R_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_address1 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            R_address1 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            R_address1 <= "XXXX";
        end if; 
    end process;


    R_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            R_ce0 <= ap_const_logic_1;
        else 
            R_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_ce1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            R_ce1 <= ap_const_logic_1;
        else 
            R_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    R_d0_assign_proc : process(ap_CS_fsm_state5, soma_7_reg_725, soma_11_reg_735, soma_15_reg_745, soma_17_reg_750, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, grp_fu_481_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            R_d0 <= soma_17_reg_750;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            R_d0 <= soma_15_reg_745;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            R_d0 <= soma_11_reg_735;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_d0 <= soma_7_reg_725;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            R_d0 <= grp_fu_481_p3;
        else 
            R_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    R_d1_assign_proc : process(soma_5_reg_720, ap_CS_fsm_state5, soma_9_reg_730, soma_13_reg_740, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, grp_fu_472_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            R_d1 <= soma_13_reg_740;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            R_d1 <= soma_9_reg_730;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            R_d1 <= soma_5_reg_720;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            R_d1 <= grp_fu_472_p3;
        else 
            R_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    R_we0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            R_we0 <= ap_const_logic_1;
        else 
            R_we0 <= ap_const_logic_0;
        end if; 
    end process;


    R_we1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            R_we1 <= ap_const_logic_1;
        else 
            R_we1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_400_p0 <= zext_ln40_5_fu_278_p1(8 - 1 downto 0);
    grp_fu_400_p1 <= zext_ln40_4_fu_274_p1(8 - 1 downto 0);
    grp_fu_408_p0 <= zext_ln40_8_fu_282_p1(8 - 1 downto 0);
    grp_fu_408_p1 <= zext_ln40_4_fu_274_p1(8 - 1 downto 0);
    grp_fu_416_p0 <= zext_ln40_11_fu_286_p1(8 - 1 downto 0);
    grp_fu_416_p1 <= zext_ln40_4_fu_274_p1(8 - 1 downto 0);
    grp_fu_424_p0 <= zext_ln40_14_fu_290_p1(8 - 1 downto 0);
    grp_fu_424_p1 <= zext_ln40_5_fu_278_p1(8 - 1 downto 0);
    grp_fu_432_p0 <= zext_ln40_14_fu_290_p1(8 - 1 downto 0);
    grp_fu_432_p1 <= zext_ln40_8_fu_282_p1(8 - 1 downto 0);
    grp_fu_440_p0 <= zext_ln40_14_fu_290_p1(8 - 1 downto 0);
    grp_fu_440_p1 <= zext_ln40_11_fu_286_p1(8 - 1 downto 0);
    grp_fu_448_p0 <= zext_ln40_17_fu_294_p1(8 - 1 downto 0);
    grp_fu_448_p1 <= zext_ln40_5_fu_278_p1(8 - 1 downto 0);
    grp_fu_456_p0 <= zext_ln40_17_fu_294_p1(8 - 1 downto 0);
    grp_fu_456_p1 <= zext_ln40_8_fu_282_p1(8 - 1 downto 0);
    grp_fu_464_p0 <= zext_ln40_17_fu_294_p1(8 - 1 downto 0);
    grp_fu_464_p1 <= zext_ln40_11_fu_286_p1(8 - 1 downto 0);
    grp_fu_472_p0 <= zext_ln40_3_fu_302_p1(8 - 1 downto 0);
    grp_fu_472_p1 <= zext_ln40_2_fu_298_p1(8 - 1 downto 0);
    grp_fu_481_p0 <= zext_ln40_7_fu_306_p1(8 - 1 downto 0);
    grp_fu_481_p1 <= zext_ln40_2_fu_298_p1(8 - 1 downto 0);
    grp_fu_490_p0 <= zext_ln40_10_fu_310_p1(8 - 1 downto 0);
    grp_fu_490_p1 <= zext_ln40_2_fu_298_p1(8 - 1 downto 0);
    grp_fu_498_p0 <= zext_ln40_13_fu_314_p1(8 - 1 downto 0);
    grp_fu_498_p1 <= zext_ln40_3_fu_302_p1(8 - 1 downto 0);
    grp_fu_506_p0 <= zext_ln40_13_fu_314_p1(8 - 1 downto 0);
    grp_fu_506_p1 <= zext_ln40_7_fu_306_p1(8 - 1 downto 0);
    grp_fu_514_p0 <= zext_ln40_13_fu_314_p1(8 - 1 downto 0);
    grp_fu_514_p1 <= zext_ln40_10_fu_310_p1(8 - 1 downto 0);
    grp_fu_522_p0 <= zext_ln40_16_fu_318_p1(8 - 1 downto 0);
    grp_fu_522_p1 <= zext_ln40_3_fu_302_p1(8 - 1 downto 0);
    grp_fu_530_p0 <= zext_ln40_16_fu_318_p1(8 - 1 downto 0);
    grp_fu_530_p1 <= zext_ln40_7_fu_306_p1(8 - 1 downto 0);
    grp_fu_538_p0 <= zext_ln40_16_fu_318_p1(8 - 1 downto 0);
    grp_fu_538_p1 <= zext_ln40_10_fu_310_p1(8 - 1 downto 0);
    soma_10_fu_372_p0 <= zext_ln40_12_fu_356_p1(8 - 1 downto 0);
    soma_10_fu_372_p1 <= zext_ln40_9_fu_346_p1(8 - 1 downto 0);
    soma_12_fu_382_p0 <= zext_ln40_15_fu_378_p1(8 - 1 downto 0);
    soma_12_fu_382_p1 <= zext_ln40_1_fu_326_p1(8 - 1 downto 0);
    soma_14_fu_388_p0 <= zext_ln40_15_fu_378_p1(8 - 1 downto 0);
    soma_14_fu_388_p1 <= zext_ln40_6_fu_336_p1(8 - 1 downto 0);
    soma_16_fu_394_p0 <= zext_ln40_15_fu_378_p1(8 - 1 downto 0);
    soma_16_fu_394_p1 <= zext_ln40_9_fu_346_p1(8 - 1 downto 0);
    soma_2_fu_340_p0 <= zext_ln40_6_fu_336_p1(8 - 1 downto 0);
    soma_2_fu_340_p1 <= zext_ln40_fu_322_p1(8 - 1 downto 0);
    soma_4_fu_350_p0 <= zext_ln40_9_fu_346_p1(8 - 1 downto 0);
    soma_4_fu_350_p1 <= zext_ln40_fu_322_p1(8 - 1 downto 0);
    soma_6_fu_360_p0 <= zext_ln40_12_fu_356_p1(8 - 1 downto 0);
    soma_6_fu_360_p1 <= zext_ln40_1_fu_326_p1(8 - 1 downto 0);
    soma_8_fu_366_p0 <= zext_ln40_12_fu_356_p1(8 - 1 downto 0);
    soma_8_fu_366_p1 <= zext_ln40_6_fu_336_p1(8 - 1 downto 0);
    soma_fu_330_p0 <= zext_ln40_1_fu_326_p1(8 - 1 downto 0);
    soma_fu_330_p1 <= zext_ln40_fu_322_p1(8 - 1 downto 0);
    zext_ln40_10_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_1_2),16));
    zext_ln40_11_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_2_2),16));
    zext_ln40_12_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_1_0),16));
    zext_ln40_13_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_1_1),16));
    zext_ln40_14_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_1_2),16));
    zext_ln40_15_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_2_0),16));
    zext_ln40_16_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_2_1),16));
    zext_ln40_17_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_2_2),16));
    zext_ln40_1_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_0_0),16));
    zext_ln40_2_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_0_1),16));
    zext_ln40_3_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_1_0),16));
    zext_ln40_4_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_0_2),16));
    zext_ln40_5_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_2_0),16));
    zext_ln40_6_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_0_1),16));
    zext_ln40_7_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_1_1),16));
    zext_ln40_8_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_2_1),16));
    zext_ln40_9_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_0_2),16));
    zext_ln40_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A_0_0),16));
end behav;
