// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_3x3_matrix_mult_3x3,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau25p-sfvb784-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.771000,HLS_SYN_LAT=29,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=288,HLS_SYN_LUT=646,HLS_VERSION=2022_2}" *)

module matrix_mult_3x3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_0_0,
        A_0_1,
        A_0_2,
        A_1_0,
        A_1_1,
        A_1_2,
        A_2_0,
        A_2_1,
        A_2_2,
        B_0_0,
        B_0_1,
        B_0_2,
        B_1_0,
        B_1_1,
        B_1_2,
        B_2_0,
        B_2_1,
        B_2_2,
        R_address0,
        R_ce0,
        R_we0,
        R_d0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] A_0_0;
input  [7:0] A_0_1;
input  [7:0] A_0_2;
input  [7:0] A_1_0;
input  [7:0] A_1_1;
input  [7:0] A_1_2;
input  [7:0] A_2_0;
input  [7:0] A_2_1;
input  [7:0] A_2_2;
input  [7:0] B_0_0;
input  [7:0] B_0_1;
input  [7:0] B_0_2;
input  [7:0] B_1_0;
input  [7:0] B_1_1;
input  [7:0] B_1_2;
input  [7:0] B_2_0;
input  [7:0] B_2_1;
input  [7:0] B_2_2;
output  [3:0] R_address0;
output   R_ce0;
output   R_we0;
output  [15:0] R_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] R_address0;
reg R_ce0;
reg R_we0;
reg[15:0] R_d0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_idle;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_ready;
wire   [3:0] grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0;
wire   [15:0] grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_idle;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_ready;
wire   [3:0] grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0;
wire   [15:0] grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_idle;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_ready;
wire   [3:0] grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0;
wire    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0;
wire   [15:0] grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0;
reg    grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg = 1'b0;
#0 grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg = 1'b0;
#0 grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg = 1'b0;
end

matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start),
    .ap_done(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done),
    .ap_idle(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_idle),
    .ap_ready(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_ready),
    .R_address0(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0),
    .R_ce0(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0),
    .R_we0(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0),
    .R_d0(grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0),
    .B_0_0_load(B_0_0),
    .B_0_1_load(B_0_1),
    .B_0_2_load(B_0_2),
    .B_1_0_load(B_1_0),
    .B_1_1_load(B_1_1),
    .B_1_2_load(B_1_2),
    .B_2_0_load(B_2_0),
    .B_2_1_load(B_2_1),
    .B_2_2_load(B_2_2),
    .zext_ln40(A_0_0),
    .zext_ln40_2(A_0_1),
    .zext_ln40_4(A_0_2)
);

matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop1 grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start),
    .ap_done(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done),
    .ap_idle(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_idle),
    .ap_ready(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_ready),
    .R_address0(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0),
    .R_ce0(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0),
    .R_we0(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0),
    .R_d0(grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0),
    .B_0_0_load(B_0_0),
    .B_0_1_load(B_0_1),
    .B_0_2_load(B_0_2),
    .B_1_0_load(B_1_0),
    .B_1_1_load(B_1_1),
    .B_1_2_load(B_1_2),
    .B_2_0_load(B_2_0),
    .B_2_1_load(B_2_1),
    .B_2_2_load(B_2_2),
    .zext_ln40_6(A_1_0),
    .zext_ln40_8(A_1_1),
    .zext_ln40_10(A_1_2)
);

matrix_mult_3x3_matrix_mult_3x3_Pipeline_coluna_loop2 grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start),
    .ap_done(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done),
    .ap_idle(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_idle),
    .ap_ready(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_ready),
    .R_address0(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0),
    .R_ce0(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0),
    .R_we0(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0),
    .R_d0(grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0),
    .B_0_0_load(B_0_0),
    .B_0_1_load(B_0_1),
    .B_0_2_load(B_0_2),
    .B_1_0_load(B_1_0),
    .B_1_1_load(B_1_1),
    .B_1_2_load(B_1_2),
    .B_2_0_load(B_2_0),
    .B_2_1_load(B_2_1),
    .B_2_2_load(B_2_2),
    .zext_ln40_12(A_2_0),
    .zext_ln40_14(A_2_1),
    .zext_ln40_16(A_2_2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg <= 1'b1;
        end else if ((grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_ready == 1'b1)) begin
            grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg <= 1'b1;
        end else if ((grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_ready == 1'b1)) begin
            grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_ready == 1'b1)) begin
            grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        R_address0 = grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        R_address0 = grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_address0 = grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_address0;
    end else begin
        R_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        R_ce0 = grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        R_ce0 = grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_ce0 = grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_ce0;
    end else begin
        R_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        R_d0 = grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        R_d0 = grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_d0 = grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_d0;
    end else begin
        R_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        R_we0 = grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_R_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        R_we0 = grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_R_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_we0 = grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_R_we0;
    end else begin
        R_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start = grp_matrix_mult_3x3_Pipeline_coluna_loop1_fu_202_ap_start_reg;

assign grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start = grp_matrix_mult_3x3_Pipeline_coluna_loop2_fu_223_ap_start_reg;

assign grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start = grp_matrix_mult_3x3_Pipeline_coluna_loop_fu_172_ap_start_reg;

endmodule //matrix_mult_3x3
