// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_3x3_matrix_mult_3x3,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau25p-sfvb784-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.771000,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=293,HLS_SYN_LUT=315,HLS_VERSION=2022_2}" *)

module matrix_mult_3x3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_0_0,
        A_0_1,
        A_0_2,
        A_1_0,
        A_1_1,
        A_1_2,
        A_2_0,
        A_2_1,
        A_2_2,
        B_0_0,
        B_0_1,
        B_0_2,
        B_1_0,
        B_1_1,
        B_1_2,
        B_2_0,
        B_2_1,
        B_2_2,
        R_0_0,
        R_0_0_ap_vld,
        R_0_1,
        R_0_1_ap_vld,
        R_0_2,
        R_0_2_ap_vld,
        R_1_0,
        R_1_0_ap_vld,
        R_1_1,
        R_1_1_ap_vld,
        R_1_2,
        R_1_2_ap_vld,
        R_2_0,
        R_2_0_ap_vld,
        R_2_1,
        R_2_1_ap_vld,
        R_2_2,
        R_2_2_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] A_0_0;
input  [7:0] A_0_1;
input  [7:0] A_0_2;
input  [7:0] A_1_0;
input  [7:0] A_1_1;
input  [7:0] A_1_2;
input  [7:0] A_2_0;
input  [7:0] A_2_1;
input  [7:0] A_2_2;
input  [7:0] B_0_0;
input  [7:0] B_0_1;
input  [7:0] B_0_2;
input  [7:0] B_1_0;
input  [7:0] B_1_1;
input  [7:0] B_1_2;
input  [7:0] B_2_0;
input  [7:0] B_2_1;
input  [7:0] B_2_2;
output  [15:0] R_0_0;
output   R_0_0_ap_vld;
output  [15:0] R_0_1;
output   R_0_1_ap_vld;
output  [15:0] R_0_2;
output   R_0_2_ap_vld;
output  [15:0] R_1_0;
output   R_1_0_ap_vld;
output  [15:0] R_1_1;
output   R_1_1_ap_vld;
output  [15:0] R_1_2;
output   R_1_2_ap_vld;
output  [15:0] R_2_0;
output   R_2_0_ap_vld;
output  [15:0] R_2_1;
output   R_2_1_ap_vld;
output  [15:0] R_2_2;
output   R_2_2_ap_vld;

reg ap_idle;
reg R_0_0_ap_vld;
reg R_0_1_ap_vld;
reg R_0_2_ap_vld;
reg R_1_0_ap_vld;
reg R_1_1_ap_vld;
reg R_1_2_ap_vld;
reg R_2_0_ap_vld;
reg R_2_1_ap_vld;
reg R_2_2_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_305_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] A_0_0_read_reg_504;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] A_0_0_read_reg_504_pp0_iter1_reg;
reg   [7:0] A_0_1_read_reg_509;
reg   [7:0] A_1_0_read_reg_514;
reg   [7:0] A_1_0_read_reg_514_pp0_iter1_reg;
reg   [7:0] A_1_1_read_reg_519;
reg   [7:0] A_2_0_read_reg_524;
reg   [7:0] A_2_0_read_reg_524_pp0_iter1_reg;
reg   [7:0] A_2_1_read_reg_529;
reg   [7:0] B_0_0_read_reg_534;
reg   [7:0] B_0_0_read_reg_534_pp0_iter1_reg;
reg   [7:0] B_0_1_read_reg_539;
reg   [7:0] B_0_1_read_reg_539_pp0_iter1_reg;
reg   [7:0] B_0_2_read_reg_544;
reg   [7:0] B_0_2_read_reg_544_pp0_iter1_reg;
reg   [7:0] B_1_0_read_reg_549;
reg   [7:0] B_1_1_read_reg_554;
reg   [7:0] B_1_2_read_reg_559;
wire   [1:0] select_ln32_fu_329_p3;
reg   [1:0] select_ln32_reg_568;
reg   [1:0] select_ln32_reg_568_pp0_iter1_reg;
reg   [1:0] select_ln32_reg_568_pp0_iter2_reg;
reg   [1:0] select_ln32_reg_568_pp0_iter3_reg;
wire   [1:0] select_ln32_1_fu_343_p3;
reg   [1:0] select_ln32_1_reg_574;
reg   [1:0] select_ln32_1_reg_574_pp0_iter1_reg;
reg   [1:0] select_ln32_1_reg_574_pp0_iter2_reg;
reg   [1:0] select_ln32_1_reg_574_pp0_iter3_reg;
wire   [15:0] mul_ln40_fu_452_p2;
wire   [15:0] grp_fu_458_p3;
reg   [1:0] j_fu_104;
wire   [1:0] add_ln34_fu_383_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
wire    ap_block_pp0_stage0;
reg   [1:0] i_fu_108;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [3:0] indvar_flatten_fu_112;
wire   [3:0] add_ln32_fu_311_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [15:0] grp_fu_466_p3;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln34_fu_323_p2;
wire   [1:0] add_ln32_1_fu_337_p2;
wire   [1:0] tmp_6_2_fu_363_p4;
wire   [7:0] tmp_6_2_fu_363_p5;
wire   [7:0] tmp_2_fu_351_p5;
wire   [7:0] tmp_6_1_fu_412_p5;
wire   [7:0] tmp_1_fu_404_p5;
wire   [7:0] tmp_6_fu_436_p5;
wire   [7:0] tmp_fu_428_p5;
wire   [7:0] mul_ln40_fu_452_p0;
wire   [7:0] mul_ln40_fu_452_p1;
wire   [7:0] grp_fu_458_p0;
wire   [7:0] grp_fu_458_p1;
wire   [7:0] grp_fu_466_p0;
wire   [7:0] grp_fu_466_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_458_p00;
wire   [15:0] grp_fu_458_p10;
wire   [15:0] grp_fu_466_p00;
wire   [15:0] grp_fu_466_p10;
wire   [15:0] mul_ln40_fu_452_p00;
wire   [15:0] mul_ln40_fu_452_p10;
reg    ap_condition_175;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U1(
    .din0(B_2_0),
    .din1(B_2_1),
    .din2(B_2_2),
    .din3(select_ln32_fu_329_p3),
    .dout(tmp_2_fu_351_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U2(
    .din0(A_0_2),
    .din1(A_1_2),
    .din2(A_2_2),
    .din3(tmp_6_2_fu_363_p4),
    .dout(tmp_6_2_fu_363_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U3(
    .din0(B_1_0_read_reg_549),
    .din1(B_1_1_read_reg_554),
    .din2(B_1_2_read_reg_559),
    .din3(select_ln32_reg_568),
    .dout(tmp_1_fu_404_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U4(
    .din0(A_0_1_read_reg_509),
    .din1(A_1_1_read_reg_519),
    .din2(A_2_1_read_reg_529),
    .din3(select_ln32_1_reg_574),
    .dout(tmp_6_1_fu_412_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U5(
    .din0(B_0_0_read_reg_534_pp0_iter1_reg),
    .din1(B_0_1_read_reg_539_pp0_iter1_reg),
    .din2(B_0_2_read_reg_544_pp0_iter1_reg),
    .din3(select_ln32_reg_568_pp0_iter1_reg),
    .dout(tmp_fu_428_p5)
);

matrix_mult_3x3_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U6(
    .din0(A_0_0_read_reg_504_pp0_iter1_reg),
    .din1(A_1_0_read_reg_514_pp0_iter1_reg),
    .din2(A_2_0_read_reg_524_pp0_iter1_reg),
    .din3(select_ln32_1_reg_574_pp0_iter1_reg),
    .dout(tmp_6_fu_436_p5)
);

matrix_mult_3x3_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U7(
    .din0(mul_ln40_fu_452_p0),
    .din1(mul_ln40_fu_452_p1),
    .dout(mul_ln40_fu_452_p2)
);

matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_458_p0),
    .din1(grp_fu_458_p1),
    .din2(mul_ln40_fu_452_p2),
    .ce(1'b1),
    .dout(grp_fu_458_p3)
);

matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_466_p0),
    .din1(grp_fu_466_p1),
    .din2(grp_fu_458_p3),
    .ce(1'b1),
    .dout(grp_fu_466_p3)
);

matrix_mult_3x3_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_175)) begin
        if ((icmp_ln32_fu_305_p2 == 1'd0)) begin
            i_fu_108 <= select_ln32_1_fu_343_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_108 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_175)) begin
        if ((icmp_ln32_fu_305_p2 == 1'd0)) begin
            indvar_flatten_fu_112 <= add_ln32_fu_311_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_112 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_175)) begin
        if ((icmp_ln32_fu_305_p2 == 1'd0)) begin
            j_fu_104 <= add_ln34_fu_383_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_104 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_0_0_read_reg_504 <= A_0_0;
        A_0_0_read_reg_504_pp0_iter1_reg <= A_0_0_read_reg_504;
        A_0_1_read_reg_509 <= A_0_1;
        A_1_0_read_reg_514 <= A_1_0;
        A_1_0_read_reg_514_pp0_iter1_reg <= A_1_0_read_reg_514;
        A_1_1_read_reg_519 <= A_1_1;
        A_2_0_read_reg_524 <= A_2_0;
        A_2_0_read_reg_524_pp0_iter1_reg <= A_2_0_read_reg_524;
        A_2_1_read_reg_529 <= A_2_1;
        B_0_0_read_reg_534 <= B_0_0;
        B_0_0_read_reg_534_pp0_iter1_reg <= B_0_0_read_reg_534;
        B_0_1_read_reg_539 <= B_0_1;
        B_0_1_read_reg_539_pp0_iter1_reg <= B_0_1_read_reg_539;
        B_0_2_read_reg_544 <= B_0_2;
        B_0_2_read_reg_544_pp0_iter1_reg <= B_0_2_read_reg_544;
        B_1_0_read_reg_549 <= B_1_0;
        B_1_1_read_reg_554 <= B_1_1;
        B_1_2_read_reg_559 <= B_1_2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln32_1_reg_574_pp0_iter1_reg <= select_ln32_1_reg_574;
        select_ln32_reg_568_pp0_iter1_reg <= select_ln32_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        select_ln32_1_reg_574_pp0_iter2_reg <= select_ln32_1_reg_574_pp0_iter1_reg;
        select_ln32_1_reg_574_pp0_iter3_reg <= select_ln32_1_reg_574_pp0_iter2_reg;
        select_ln32_reg_568_pp0_iter2_reg <= select_ln32_reg_568_pp0_iter1_reg;
        select_ln32_reg_568_pp0_iter3_reg <= select_ln32_reg_568_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_305_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln32_1_reg_574 <= select_ln32_1_fu_343_p3;
        select_ln32_reg_568 <= select_ln32_fu_329_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_1_reg_574_pp0_iter3_reg == 2'd0) & (select_ln32_reg_568_pp0_iter3_reg == 2'd0))) begin
        R_0_0_ap_vld = 1'b1;
    end else begin
        R_0_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_1_reg_574_pp0_iter3_reg == 2'd0) & (select_ln32_reg_568_pp0_iter3_reg == 2'd1))) begin
        R_0_1_ap_vld = 1'b1;
    end else begin
        R_0_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln32_reg_568_pp0_iter3_reg == 2'd0) & ~(select_ln32_reg_568_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_1_reg_574_pp0_iter3_reg == 2'd0))) begin
        R_0_2_ap_vld = 1'b1;
    end else begin
        R_0_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_1_reg_574_pp0_iter3_reg == 2'd1) & (select_ln32_reg_568_pp0_iter3_reg == 2'd0))) begin
        R_1_0_ap_vld = 1'b1;
    end else begin
        R_1_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_1_reg_574_pp0_iter3_reg == 2'd1) & (select_ln32_reg_568_pp0_iter3_reg == 2'd1))) begin
        R_1_1_ap_vld = 1'b1;
    end else begin
        R_1_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln32_reg_568_pp0_iter3_reg == 2'd0) & ~(select_ln32_reg_568_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_1_reg_574_pp0_iter3_reg == 2'd1))) begin
        R_1_2_ap_vld = 1'b1;
    end else begin
        R_1_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln32_1_reg_574_pp0_iter3_reg == 2'd0) & ~(select_ln32_1_reg_574_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_reg_568_pp0_iter3_reg == 2'd0))) begin
        R_2_0_ap_vld = 1'b1;
    end else begin
        R_2_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln32_1_reg_574_pp0_iter3_reg == 2'd0) & ~(select_ln32_1_reg_574_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln32_reg_568_pp0_iter3_reg == 2'd1))) begin
        R_2_1_ap_vld = 1'b1;
    end else begin
        R_2_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln32_1_reg_574_pp0_iter3_reg == 2'd0) & ~(select_ln32_reg_568_pp0_iter3_reg == 2'd0) & ~(select_ln32_reg_568_pp0_iter3_reg == 2'd1) & ~(select_ln32_1_reg_574_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_2_2_ap_vld = 1'b1;
    end else begin
        R_2_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_305_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_104;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_0_0 = grp_fu_466_p3;

assign R_0_1 = grp_fu_466_p3;

assign R_0_2 = grp_fu_466_p3;

assign R_1_0 = grp_fu_466_p3;

assign R_1_1 = grp_fu_466_p3;

assign R_1_2 = grp_fu_466_p3;

assign R_2_0 = grp_fu_466_p3;

assign R_2_1 = grp_fu_466_p3;

assign R_2_2 = grp_fu_466_p3;

assign add_ln32_1_fu_337_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign add_ln32_fu_311_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln34_fu_383_p2 = (select_ln32_fu_329_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_175 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_458_p0 = grp_fu_458_p00;

assign grp_fu_458_p00 = tmp_2_fu_351_p5;

assign grp_fu_458_p1 = grp_fu_458_p10;

assign grp_fu_458_p10 = tmp_6_2_fu_363_p5;

assign grp_fu_466_p0 = grp_fu_466_p00;

assign grp_fu_466_p00 = tmp_1_fu_404_p5;

assign grp_fu_466_p1 = grp_fu_466_p10;

assign grp_fu_466_p10 = tmp_6_1_fu_412_p5;

assign icmp_ln32_fu_305_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_323_p2 = ((ap_sig_allocacmp_j_load == 2'd3) ? 1'b1 : 1'b0);

assign mul_ln40_fu_452_p0 = mul_ln40_fu_452_p00;

assign mul_ln40_fu_452_p00 = tmp_fu_428_p5;

assign mul_ln40_fu_452_p1 = mul_ln40_fu_452_p10;

assign mul_ln40_fu_452_p10 = tmp_6_fu_436_p5;

assign select_ln32_1_fu_343_p3 = ((icmp_ln34_fu_323_p2[0:0] == 1'b1) ? add_ln32_1_fu_337_p2 : ap_sig_allocacmp_i_load);

assign select_ln32_fu_329_p3 = ((icmp_ln34_fu_323_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign tmp_6_2_fu_363_p4 = ((icmp_ln34_fu_323_p2[0:0] == 1'b1) ? add_ln32_1_fu_337_p2 : ap_sig_allocacmp_i_load);

endmodule //matrix_mult_3x3
