// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_3x3_matrix_mult_3x3,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau25p-sfvb784-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.101000,HLS_SYN_LAT=23,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=106,HLS_SYN_LUT=356,HLS_VERSION=2022_2}" *)

module matrix_mult_3x3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        R_address0,
        R_ce0,
        R_we0,
        R_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [3:0] A_address1;
output   A_ce1;
input  [7:0] A_q1;
output  [3:0] B_address0;
output   B_ce0;
input  [7:0] B_q0;
output  [3:0] B_address1;
output   B_ce1;
input  [7:0] B_q1;
output  [3:0] R_address0;
output   R_ce0;
output   R_we0;
output  [15:0] R_d0;

reg ap_idle;
reg[3:0] A_address0;
reg A_ce0;
reg A_ce1;
reg[3:0] B_address0;
reg B_ce0;
reg B_ce1;
reg R_ce0;
reg R_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln32_reg_446;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] reg_151;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] reg_156;
wire   [0:0] icmp_ln32_fu_200_p2;
wire   [1:0] select_ln32_fu_227_p3;
reg   [1:0] select_ln32_reg_450;
wire   [3:0] select_ln32_2_fu_279_p3;
reg   [3:0] select_ln32_2_reg_455;
wire   [3:0] add_ln43_fu_339_p2;
reg   [3:0] add_ln43_reg_480;
reg   [3:0] add_ln43_reg_480_pp0_iter1_reg;
reg   [3:0] add_ln43_reg_480_pp0_iter2_reg;
wire   [15:0] soma_fu_398_p2;
wire   [15:0] grp_fu_408_p3;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] add_ln32_1_cast_fu_293_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] add_ln32_2_cast_fu_304_p1;
wire   [63:0] zext_ln40_5_fu_323_p1;
wire   [63:0] zext_ln40_6_fu_334_p1;
wire   [63:0] select_ln32_2_cast_fu_366_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln34_fu_374_p1;
wire   [63:0] zext_ln43_1_fu_404_p1;
reg   [1:0] j_fu_60;
wire   [1:0] add_ln34_fu_345_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [1:0] i_fu_64;
wire   [1:0] select_ln32_1_fu_253_p3;
reg   [1:0] ap_sig_allocacmp_i_1;
reg   [3:0] indvar_flatten_fu_68;
wire   [3:0] add_ln32_3_fu_206_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [15:0] grp_fu_416_p3;
wire   [3:0] tmp_fu_186_p3;
wire   [3:0] i_cast_fu_182_p1;
wire   [0:0] icmp_ln34_fu_221_p2;
wire   [1:0] add_ln32_fu_215_p2;
wire   [3:0] tmp_1_fu_239_p3;
wire   [3:0] add_ln32_cast_fu_235_p1;
wire   [3:0] tmp_2_fu_265_p3;
wire   [3:0] zext_ln43_fu_261_p1;
wire   [3:0] empty_7_fu_247_p2;
wire   [3:0] empty_fu_194_p2;
wire   [3:0] add_ln32_1_fu_287_p2;
wire   [3:0] add_ln32_2_fu_298_p2;
wire   [2:0] zext_ln40_4_fu_313_p1;
wire   [2:0] add_ln40_1_fu_317_p2;
wire   [3:0] zext_ln40_3_fu_309_p1;
wire   [3:0] add_ln40_2_fu_328_p2;
wire   [3:0] sub_ln43_fu_273_p2;
wire   [7:0] soma_fu_398_p0;
wire   [7:0] soma_fu_398_p1;
wire   [7:0] grp_fu_408_p0;
wire   [7:0] grp_fu_408_p1;
wire   [7:0] grp_fu_416_p0;
wire   [7:0] grp_fu_416_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_408_p00;
wire   [15:0] grp_fu_408_p10;
wire   [15:0] grp_fu_416_p00;
wire   [15:0] grp_fu_416_p10;
wire   [15:0] soma_fu_398_p00;
wire   [15:0] soma_fu_398_p10;
reg    ap_condition_173;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_3x3_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U1(
    .din0(soma_fu_398_p0),
    .din1(soma_fu_398_p1),
    .dout(soma_fu_398_p2)
);

matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_408_p0),
    .din1(grp_fu_408_p1),
    .din2(soma_fu_398_p2),
    .ce(1'b1),
    .dout(grp_fu_408_p3)
);

matrix_mult_3x3_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_416_p0),
    .din1(grp_fu_416_p1),
    .din2(grp_fu_408_p3),
    .ce(1'b1),
    .dout(grp_fu_416_p3)
);

matrix_mult_3x3_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_173)) begin
        if ((icmp_ln32_fu_200_p2 == 1'd0)) begin
            i_fu_64 <= select_ln32_1_fu_253_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_173)) begin
        if ((icmp_ln32_fu_200_p2 == 1'd0)) begin
            indvar_flatten_fu_68 <= add_ln32_3_fu_206_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_68 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_173)) begin
        if ((icmp_ln32_fu_200_p2 == 1'd0)) begin
            j_fu_60 <= add_ln34_fu_345_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_60 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_151 <= A_q0;
    end else if (((icmp_ln32_reg_446 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_151 <= A_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_156 <= B_q0;
    end else if (((icmp_ln32_reg_446 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_156 <= B_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_200_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln43_reg_480 <= add_ln43_fu_339_p2;
        select_ln32_2_reg_455 <= select_ln32_2_fu_279_p3;
        select_ln32_reg_450 <= select_ln32_fu_227_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln43_reg_480_pp0_iter1_reg <= add_ln43_reg_480;
        add_ln43_reg_480_pp0_iter2_reg <= add_ln43_reg_480_pp0_iter1_reg;
        icmp_ln32_reg_446 <= icmp_ln32_fu_200_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            A_address0 = select_ln32_2_cast_fu_366_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            A_address0 = add_ln32_2_cast_fu_304_p1;
        end else begin
            A_address0 = 'bx;
        end
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce1 = 1'b1;
    end else begin
        A_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            B_address0 = zext_ln34_fu_374_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            B_address0 = zext_ln40_6_fu_334_p1;
        end else begin
            B_address0 = 'bx;
        end
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        B_ce0 = 1'b1;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce1 = 1'b1;
    end else begin
        B_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        R_ce0 = 1'b1;
    end else begin
        R_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        R_we0 = 1'b1;
    end else begin
        R_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_reg_446 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_60;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address1 = add_ln32_1_cast_fu_293_p1;

assign B_address1 = zext_ln40_5_fu_323_p1;

assign R_address0 = zext_ln43_1_fu_404_p1;

assign R_d0 = grp_fu_416_p3;

assign add_ln32_1_cast_fu_293_p1 = add_ln32_1_fu_287_p2;

assign add_ln32_1_fu_287_p2 = (select_ln32_2_fu_279_p3 + 4'd1);

assign add_ln32_2_cast_fu_304_p1 = add_ln32_2_fu_298_p2;

assign add_ln32_2_fu_298_p2 = (select_ln32_2_fu_279_p3 + 4'd2);

assign add_ln32_3_fu_206_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln32_cast_fu_235_p1 = add_ln32_fu_215_p2;

assign add_ln32_fu_215_p2 = (ap_sig_allocacmp_i_1 + 2'd1);

assign add_ln34_fu_345_p2 = (select_ln32_fu_227_p3 + 2'd1);

assign add_ln40_1_fu_317_p2 = (zext_ln40_4_fu_313_p1 + 3'd3);

assign add_ln40_2_fu_328_p2 = (zext_ln40_3_fu_309_p1 + 4'd6);

assign add_ln43_fu_339_p2 = (sub_ln43_fu_273_p2 + zext_ln40_3_fu_309_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_173 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign empty_7_fu_247_p2 = (tmp_1_fu_239_p3 - add_ln32_cast_fu_235_p1);

assign empty_fu_194_p2 = (tmp_fu_186_p3 - i_cast_fu_182_p1);

assign grp_fu_408_p0 = grp_fu_408_p00;

assign grp_fu_408_p00 = B_q0;

assign grp_fu_408_p1 = grp_fu_408_p10;

assign grp_fu_408_p10 = A_q0;

assign grp_fu_416_p0 = grp_fu_416_p00;

assign grp_fu_416_p00 = reg_156;

assign grp_fu_416_p1 = grp_fu_416_p10;

assign grp_fu_416_p10 = reg_151;

assign i_cast_fu_182_p1 = ap_sig_allocacmp_i_1;

assign icmp_ln32_fu_200_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_221_p2 = ((ap_sig_allocacmp_j_load == 2'd3) ? 1'b1 : 1'b0);

assign select_ln32_1_fu_253_p3 = ((icmp_ln34_fu_221_p2[0:0] == 1'b1) ? add_ln32_fu_215_p2 : ap_sig_allocacmp_i_1);

assign select_ln32_2_cast_fu_366_p1 = select_ln32_2_reg_455;

assign select_ln32_2_fu_279_p3 = ((icmp_ln34_fu_221_p2[0:0] == 1'b1) ? empty_7_fu_247_p2 : empty_fu_194_p2);

assign select_ln32_fu_227_p3 = ((icmp_ln34_fu_221_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign soma_fu_398_p0 = soma_fu_398_p00;

assign soma_fu_398_p00 = reg_156;

assign soma_fu_398_p1 = soma_fu_398_p10;

assign soma_fu_398_p10 = reg_151;

assign sub_ln43_fu_273_p2 = (tmp_2_fu_265_p3 - zext_ln43_fu_261_p1);

assign tmp_1_fu_239_p3 = {{add_ln32_fu_215_p2}, {2'd0}};

assign tmp_2_fu_265_p3 = {{select_ln32_1_fu_253_p3}, {2'd0}};

assign tmp_fu_186_p3 = {{ap_sig_allocacmp_i_1}, {2'd0}};

assign zext_ln34_fu_374_p1 = select_ln32_reg_450;

assign zext_ln40_3_fu_309_p1 = select_ln32_fu_227_p3;

assign zext_ln40_4_fu_313_p1 = select_ln32_fu_227_p3;

assign zext_ln40_5_fu_323_p1 = add_ln40_1_fu_317_p2;

assign zext_ln40_6_fu_334_p1 = add_ln40_2_fu_328_p2;

assign zext_ln43_1_fu_404_p1 = add_ln43_reg_480_pp0_iter2_reg;

assign zext_ln43_fu_261_p1 = select_ln32_1_fu_253_p3;

endmodule //matrix_mult_3x3
